[package]
name = "gameoflife"
version = "0.1.0"
authors = ["Ben Wallis <atomyc@gmail.com>"]

[[bin]]
name = "gameoflife"

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.48.0"
piston2d-opengl_graphics = "0.54.0"
rand = "0.5.5"